#!/data/data/com.termux/files/usr/bin/sh
# mcl-s-rdc-channel-watchdog-run:v1
PREFIX=/data/data/com.termux/files/usr
HOME=/data/data/com.termux/files/home
exec 2>&1
while :; do
  "$HOME/.local/bin/rdc-health-watchdog" || true
  "$PREFIX/bin/sleep" 30
done
