'use strict';

const NEXT_ACTIONS = Object.freeze({
  NONE: 'NONE',
  WAIT_FOR_CURRENT_EVIDENCE: 'WAIT_FOR_CURRENT_EVIDENCE',
  RECHECK_AFTER_COOLDOWN: 'RECHECK_AFTER_COOLDOWN',
  REVIEW_CHANGED_GOVERNANCE_PATHS: 'REVIEW_CHANGED_GOVERNANCE_PATHS',
  REVIEW_CHANGED_PRODUCT_RUNTIME_PATHS: 'REVIEW_CHANGED_PRODUCT_RUNTIME_PATHS',
  OPEN_ADMIN_CAPABILITY_REVIEW: 'OPEN_ADMIN_CAPABILITY_REVIEW',
  RESOLVE_PACKET_SCOPE_OVERLAP: 'RESOLVE_PACKET_SCOPE_OVERLAP',
  REVIEW_REQUIRED_CHECK_FAILURE: 'REVIEW_REQUIRED_CHECK_FAILURE',
  REVIEW_PRODUCTION_AUTHORITY_MISMATCH: 'REVIEW_PRODUCTION_AUTHORITY_MISMATCH',
  REVIEW_CURRENT_INCIDENT: 'REVIEW_CURRENT_INCIDENT',
  REVIEW_CURRENT_ATTENTION: 'REVIEW_CURRENT_ATTENTION',
});

const NEXT_ACTION_SET = new Set(Object.values(NEXT_ACTIONS));

const REASON_ACTIONS = Object.freeze({
  REQUIRED_CHECK_FAILED: NEXT_ACTIONS.REVIEW_REQUIRED_CHECK_FAILURE,
  RELEASE_AUTHORITY_IDENTITY_MISMATCH: NEXT_ACTIONS.REVIEW_PRODUCTION_AUTHORITY_MISMATCH,
  PRODUCTION_AUTHORITY_MISMATCH: NEXT_ACTIONS.REVIEW_PRODUCTION_AUTHORITY_MISMATCH,
  AUTHORITY_INTEGRITY_FAILED: NEXT_ACTIONS.REVIEW_PRODUCTION_AUTHORITY_MISMATCH,
  ADMINISTRATION_WRITE_UNAVAILABLE: NEXT_ACTIONS.OPEN_ADMIN_CAPABILITY_REVIEW,
  BLOCKED_PERMISSION: NEXT_ACTIONS.OPEN_ADMIN_CAPABILITY_REVIEW,
  PACKET_SCOPE_OVERLAP: NEXT_ACTIONS.RESOLVE_PACKET_SCOPE_OVERLAP,
  WORK_PACKET_SCOPE_OVERLAP: NEXT_ACTIONS.RESOLVE_PACKET_SCOPE_OVERLAP,
  DEFERRED_COOLDOWN: NEXT_ACTIONS.RECHECK_AFTER_COOLDOWN,
  CAPABILITY_RETRY_COOLDOWN: NEXT_ACTIONS.RECHECK_AFTER_COOLDOWN,
  EVIDENCE_SETTLING: NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE,
  EVIDENCE_UNKNOWN: NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE,
  CONVERGENCE_STALE: NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE,
});

function normalizeCode(value) {
  return String(value || '').trim().toUpperCase();
}

function isRepositoryNextAction(value) {
  return NEXT_ACTION_SET.has(String(value || '').trim());
}

function nextActionForBlock({blockingClass, reasonCode} = {}) {
  const reason = normalizeCode(reasonCode);
  if (REASON_ACTIONS[reason]) return REASON_ACTIONS[reason];

  switch (normalizeCode(blockingClass)) {
    case 'SETTLING':
    case 'STALE_CONVERGENCE':
    case 'UNKNOWN':
      return NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE;
    case 'ATTENTION':
      return NEXT_ACTIONS.REVIEW_CURRENT_ATTENTION;
    case 'INCIDENT':
      return NEXT_ACTIONS.REVIEW_CURRENT_INCIDENT;
    default:
      return NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE;
  }
}

function nextActionForRisk(riskLevel) {
  switch (normalizeCode(riskLevel)) {
    case 'HIGH':
      return NEXT_ACTIONS.REVIEW_CHANGED_GOVERNANCE_PATHS;
    case 'MEDIUM':
      return NEXT_ACTIONS.REVIEW_CHANGED_PRODUCT_RUNTIME_PATHS;
    case 'LOW':
    case 'NONE':
      return NEXT_ACTIONS.NONE;
    default:
      return NEXT_ACTIONS.WAIT_FOR_CURRENT_EVIDENCE;
  }
}

module.exports = {
  NEXT_ACTIONS,
  REASON_ACTIONS,
  isRepositoryNextAction,
  nextActionForBlock,
  nextActionForRisk,
  normalizeCode,
};
