from __future__ import annotations

import argparse
import json
import os
import shlex
import sys
from pathlib import Path
from typing import Iterable

import notifier

SUPPORTED_SHELLS = {"bash", "zsh"}
CONFIG_DIR = Path(".config") / "taskbridge"
MARKER_START = "# >>> taskbridge shell-notify >>>"
MARKER_END = "# <<< taskbridge shell-notify <<<"


def _home_path(home: Path | str | None = None) -> Path:
    return Path.home() if home is None else Path(home)


def detect_shell(shell: str | None = None) -> str:
    if shell:
        value = Path(shell).name
    else:
        value = Path(os.environ.get("SHELL", "")).name
    if value not in SUPPORTED_SHELLS:
        raise ValueError("supported shell required: bash or zsh (use --shell if $SHELL is unavailable)")
    return value


def rc_path(shell: str, home: Path | str | None = None) -> Path:
    root = _home_path(home)
    return root / (".bashrc" if shell == "bash" else ".zshrc")


def installed_hook_path(shell: str, home: Path | str | None = None) -> Path:
    return _home_path(home) / CONFIG_DIR / f"shell-notify.{shell}"


def _template_path(shell: str) -> Path:
    return Path(__file__).resolve().with_name("shell-hooks") / f"taskbridge-{shell}.sh"


def _owned_block(shell: str) -> str:
    suffix = "bash" if shell == "bash" else "zsh"
    hook_line = f'$HOME/.config/taskbridge/shell-notify.{suffix}'
    if shell == "zsh":
        return "\n".join(
            [
                MARKER_START,
                f'[ -r "{hook_line}" ] && . "{hook_line}"',
                MARKER_END,
            ]
        )
    return "\n".join(
        [
            MARKER_START,
            'if [[ ${__TASKBRIDGE_SHELL_NOTIFY_LOADED:-0} != 1 ]]; then',
            '  __taskbridge_debug_probe="${TMPDIR:-/tmp}/.taskbridge-debug-trap.$$"',
            '  trap -p DEBUG > "$__taskbridge_debug_probe" 2>/dev/null || true',
            '  if [[ -s $__taskbridge_debug_probe ]]; then',
            "    printf '%s\\n' 'TaskBridge shell-notify: existing DEBUG trap detected; hook not activated.' >&2",
            '  elif [[ -r "$HOME/.config/taskbridge/shell-notify.bash" ]]; then',
            '    __TASKBRIDGE_DEBUG_TRAP_CLEAR=1',
            '    . "$HOME/.config/taskbridge/shell-notify.bash"',
            '    unset __TASKBRIDGE_DEBUG_TRAP_CLEAR',
            '  fi',
            '  rm -f -- "$__taskbridge_debug_probe"',
            '  unset __taskbridge_debug_probe',
            'fi',
            MARKER_END,
        ]
    )


def _strip_owned_block(text: str) -> str:
    result = text
    while True:
        start = result.find(MARKER_START)
        if start < 0:
            return result
        end = result.find(MARKER_END, start + len(MARKER_START))
        if end < 0:
            return result
        end += len(MARKER_END)
        if result[end : end + 2] == "\r\n":
            end += 2
        elif result[end : end + 1] == "\n":
            end += 1
        result = result[:start] + result[end:]


def _render_hook(shell: str, min_seconds: int, *, python_exe: str | None = None, script_path: Path | str | None = None) -> str:
    if min_seconds < 0:
        raise ValueError("--min-seconds must be >= 0")
    template = _template_path(shell).read_text()
    python_value = python_exe or sys.executable
    script_value = str(Path(script_path or __file__).resolve())
    header = "\n".join(
        [
            "# Generated by TaskBridge. Do not edit; reinstall instead.",
            f"__TASKBRIDGE_PYTHON={shlex.quote(python_value)}",
            f"__TASKBRIDGE_SHELL_NOTIFY_SCRIPT={shlex.quote(script_value)}",
            f"__TASKBRIDGE_MIN_SECONDS={int(min_seconds)}",
            "",
        ]
    )
    return header + template.rstrip() + "\n"


def install(shell: str | None = None, min_seconds: int = 10, *, home: Path | str | None = None) -> dict:
    shell_name = detect_shell(shell)
    root = _home_path(home)
    hook = installed_hook_path(shell_name, root)
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(_render_hook(shell_name, min_seconds))
    hook.chmod(0o600)

    rc = rc_path(shell_name, root)
    original = rc.read_text(errors="replace") if rc.exists() else ""
    cleaned = _strip_owned_block(original)
    if cleaned and not cleaned.endswith("\n"):
        cleaned += "\n"
    new_text = cleaned + _owned_block(shell_name) + "\n"
    rc.write_text(new_text)

    return status(shell_name, home=root)


def status(shell: str | None = None, *, home: Path | str | None = None) -> dict:
    shell_name = detect_shell(shell)
    root = _home_path(home)
    rc = rc_path(shell_name, root)
    hook = installed_hook_path(shell_name, root)
    text = rc.read_text(errors="replace") if rc.exists() else ""
    return {
        "shell": shell_name,
        "installed": hook.exists() and MARKER_START in text and MARKER_END in text,
        "hook_path": str(hook),
        "rc_path": str(rc),
        "hook_exists": hook.exists(),
        "rc_marker": MARKER_START in text and MARKER_END in text,
        "notification_available": notifier.available(),
        "activation_note": f"Open a new {shell_name} session or source {rc.name} to activate the hook.",
    }


def remove(shell: str | None = None, *, home: Path | str | None = None) -> dict:
    root = _home_path(home)
    shells: Iterable[str] = [detect_shell(shell)] if shell else sorted(SUPPORTED_SHELLS)
    removed: list[str] = []
    for shell_name in shells:
        rc = rc_path(shell_name, root)
        if rc.exists():
            before = rc.read_text(errors="replace")
            after = _strip_owned_block(before)
            if after != before:
                rc.write_text(after)
                removed.append(str(rc))
        hook = installed_hook_path(shell_name, root)
        if hook.exists():
            hook.unlink()
            removed.append(str(hook))
    return {"removed": removed, "home": str(root)}


def safe_label(raw: str | None) -> str:
    if not raw:
        return "Termux 명령"
    token = raw.strip().split(None, 1)[0] if raw.strip() else ""
    token = token.rsplit("/", 1)[-1]
    if not token or "=" in token:
        return "Termux 명령"
    allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._+-"
    if any(ch not in allowed for ch in token):
        return "Termux 명령"
    if token.startswith("__taskbridge") or token in {"trap", "PROMPT_COMMAND"}:
        return "Termux 명령"
    return token[:48]


def emit(status_code: int, label: str | None, elapsed: int, shell_pid: int) -> bool:
    clean = safe_label(label)
    if status_code == 0:
        title = "Termux 작업 완료"
        content = f"{clean} · 완료"
    else:
        title = "Termux 작업 실패"
        content = f"{clean} · exit {status_code}"
    if elapsed > 0:
        content += f" · {elapsed}s"
    return notifier.notify(title, content, notification_id=f"taskbridge-shell-{shell_pid}")


def _parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="shell_notify", description="TaskBridge interactive shell completion notifications")
    sub = p.add_subparsers(dest="cmd", required=True)

    install_p = sub.add_parser("install", help="install the interactive shell completion hook")
    install_p.add_argument("--shell", choices=sorted(SUPPORTED_SHELLS))
    install_p.add_argument("--min-seconds", type=int, default=10)

    status_p = sub.add_parser("status", help="show shell notification hook status")
    status_p.add_argument("--shell", choices=sorted(SUPPORTED_SHELLS))

    remove_p = sub.add_parser("remove", help="remove TaskBridge-owned shell notification integration")
    remove_p.add_argument("--shell", choices=sorted(SUPPORTED_SHELLS))

    emit_p = sub.add_parser("emit", help=argparse.SUPPRESS)
    emit_p.add_argument("--status", type=int, required=True)
    emit_p.add_argument("--label")
    emit_p.add_argument("--elapsed", type=int, default=0)
    emit_p.add_argument("--shell-pid", type=int, required=True)
    return p


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.cmd == "install":
            print(json.dumps(install(args.shell, args.min_seconds), indent=2, ensure_ascii=False))
            return 0
        if args.cmd == "status":
            print(json.dumps(status(args.shell), indent=2, ensure_ascii=False))
            return 0
        if args.cmd == "remove":
            print(json.dumps(remove(args.shell), indent=2, ensure_ascii=False))
            return 0
        if args.cmd == "emit":
            emit(args.status, args.label, max(0, args.elapsed), args.shell_pid)
            return 0
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
