from pathlib import Path

for name in ['plugins/simcore/latest.js', 'plugins/simcore/install.js']:
    p = Path(name)
    s = p.read_text()
    assert '//@version 0.62.18' in s, name
    s = s.replace('//@version 0.62.18','//@version 0.62.19',1)
    s = s.replace('//@display-name SimCore v0.62.18 Compact Diagnostics Panel','//@display-name SimCore v0.62.19 Narrative Clock Guard Phase 1',1)
    old='''// v0.62.18 Compact Diagnostics Panel:\n// - Runtime/state/storage/output behavior remains unchanged\n// - Adds a compact operational summary with current snapshot path and top-level request/output timing\n// - Detailed beforeRequest/output timing and reaction_max tables are collapsed by default\n// - Renames Last history restore to Last snapshot restore for rewind/repeat-send accuracy\n// - No snapshot format/state schema/Core prompt/lifecycle/community/reaction changes, no new storage I/O'''
    new='''// v0.62.19 Narrative Clock Guard Phase 1:\n// - Adds a conservative current-narrative timestamp anchor for non-broadcast modes\n// - Activates only when the user opens with a clear forward calendar/relative-time transition\n// - When active, the next current timestamp may not precede the previous non-broadcast timestamp\n// - Embedded preview/flashback/event time must not replace the current narrative timestamp\n// - No calendar guessing for ambiguous week/day phrases; no Broadcast/Community/Reaction behavior changes'''
    assert old in s, name
    s=s.replace(old,new,1)
    s=s.replace('const CORE_STATE_VERSION = 8;','const CORE_STATE_VERSION = 9;',1)
    s=s.replace('''    worldYear: null,\n    koreanAgeOffset: 0,\n    clockRepairVersion: 0,''','''    worldYear: null,\n    koreanAgeOffset: 0,\n    narrativeTimestamp: null,\n    narrativeClockVersion: 1,\n    clockRepairVersion: 0,''',1)
    s=s.replace('''  s.worldYear = legacyYear != null && Number.isFinite(Number(legacyYear)) ? Number(legacyYear) : null;\n  s.koreanAgeOffset = Math.max(0, Math.round(Number(s.koreanAgeOffset) || 0));\n  s.clockRepairVersion = Math.max(0, Math.round(Number(s.clockRepairVersion) || 0));''','''  s.worldYear = legacyYear != null && Number.isFinite(Number(legacyYear)) ? Number(legacyYear) : null;\n  s.koreanAgeOffset = Math.max(0, Math.round(Number(s.koreanAgeOffset) || 0));\n  s.narrativeTimestamp = typeof s.narrativeTimestamp === 'string' && s.narrativeTimestamp.trim() ? s.narrativeTimestamp.trim() : null;\n  s.narrativeClockVersion = Math.max(1, Math.round(Number(s.narrativeClockVersion) || 0));\n  s.clockRepairVersion = Math.max(0, Math.round(Number(s.clockRepairVersion) || 0));''',1)
    needle='''function applyWorldYear(state, year) {\n  if (year == null || year === '') return false;\n  const y = Number(year);\n  if (!Number.isFinite(y)) return false;\n  const prev = state.worldYear;\n  if (prev == null) {\n    state.worldYear = y;\n    return true;\n  }\n  if (y > prev) {\n    state.koreanAgeOffset += y - prev;\n    state.worldYear = y;\n    return true;\n  }\n  return false;\n}\n\nmodule.exports = {'''
    rep='''function applyWorldYear(state, year) {\n  if (year == null || year === '') return false;\n  const y = Number(year);\n  if (!Number.isFinite(y)) return false;\n  const prev = state.worldYear;\n  if (prev == null) {\n    state.worldYear = y;\n    return true;\n  }\n  if (y > prev) {\n    state.koreanAgeOffset += y - prev;\n    state.worldYear = y;\n    return true;\n  }\n  return false;\n}\n\n// Phase 1 is intentionally relational, not a full Korean calendar parser.\n// Only a clear opening current-time transition activates the forward guard.\nfunction narrativeProgressionHint(userText) {\n  const head = String(userText || '').trim().slice(0, 420);\n  if (!head) return { active: false, reason: 'none' };\n  const lead = '(?:한편\\\\s+)?(?:그리고\\\\s+)?';\n  const weekday = '(?:월|화|수|목|금|토|일)요일';\n  const weekWord = '(?:\\\\d{1,2}주차|첫째\\\\s*주|둘째\\\\s*주|셋째\\\\s*주|넷째\\\\s*주|다섯째\\\\s*주|마지막\\\\s*주)';\n  const calendar = `(?:\\\\d{4}년\\\\s*)?\\\\d{1,2}월(?:\\\\s*${weekWord})?(?:\\\\s*${weekday})?`;\n  const namedWeek = `(?:(?:그|이번|다음)\\\\s*주)(?:\\\\s*${weekday})?`;\n  const dayOnly = `(?:${weekday}|오늘|내일|모레|다음\\\\s*날|이튿날)`;\n  const transition = new RegExp(`^${lead}(?:${calendar}|${namedWeek}|${dayOnly})\\\\s*(?:이|가)?\\\\s*(?:되고|되어|되면서|되었다|됐다)(?:\\\\s|$)`, 'i');\n  if (transition.test(head)) return { active: true, reason: 'calendar-transition' };\n\n  const relative = new RegExp(`^${lead}(?:(?:며칠|\\\\d+\\\\s*(?:일|주|개월|달|년))\\\\s*(?:뒤|후)|다음\\\\s*(?:달|주))(?:(?:이|가)?\\\\s*(?:되고|되어|지나|흘러))?(?:\\\\s|$)`, 'i');\n  if (relative.test(head)) return { active: true, reason: 'relative-forward' };\n  return { active: false, reason: 'none' };\n}\n\nfunction commitNarrativeTimestamp(state, pending, content) {\n  if (/^B_/.test(String(pending?.mode || ''))) return { changed: false, reason: 'broadcast', timestamp: null };\n  const parsed = parseTimestamp(content);\n  if (!parsed) return { changed: false, reason: 'missing-or-invalid', timestamp: null };\n  const current = parsed.raw;\n  const previous = pending?.narrativeTimestampPrevious || state.narrativeTimestamp || null;\n  if (pending?.narrativeClockGuard && previous) {\n    const cmp = compareTimestamps(current, previous);\n    if (cmp != null && cmp < 0) return { changed: false, reason: 'backward', timestamp: current, previous };\n  }\n  const changed = state.narrativeTimestamp !== current;\n  state.narrativeTimestamp = current;\n  return { changed, reason: 'committed', timestamp: current, previous };\n}\n\nfunction syncNarrativeTimestamp(state, content, mode) {\n  if (/^B_/.test(String(mode || ''))) return false;\n  const parsed = parseTimestamp(content);\n  if (!parsed) return false;\n  const changed = state.narrativeTimestamp !== parsed.raw;\n  state.narrativeTimestamp = parsed.raw;\n  return changed;\n}\n\nmodule.exports = {'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    s=s.replace('''  commitBroadcastAirtime,\n  applyWorldYear,''','''  commitBroadcastAirtime,\n  narrativeProgressionHint,\n  commitNarrativeTimestamp,\n  syncNarrativeTimestamp,\n  applyWorldYear,''',1)
    needle='''  const secondaryConfigured = !!(config.secondaryName && config.secondaryKeyword);\n  const secondaryActive = secondaryConfigured && input.includes(config.secondaryKeyword);\n\n  // Explicit user dates can advance world year before generation in every mode.\n  time.applyWorldYear(state, time.explicitWorldYear(input));'''
    rep='''  const secondaryConfigured = !!(config.secondaryName && config.secondaryKeyword);\n  const secondaryActive = secondaryConfigured && input.includes(config.secondaryKeyword);\n  const narrativeProgression = /^B_/.test(c.mode) ? { active: false, reason: 'broadcast' } : time.narrativeProgressionHint(input);\n  const narrativeTimestampPrevious = /^B_/.test(c.mode) ? null : (state.narrativeTimestamp || null);\n  const narrativeClockGuard = !!(narrativeProgression.active && narrativeTimestampPrevious);\n\n  // Explicit user dates can advance world year before generation in every mode.\n  time.applyWorldYear(state, time.explicitWorldYear(input));'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    s=s.replace('''    secondaryName: config.secondaryName,\n    secondaryKeyword: config.secondaryKeyword,''','''    secondaryName: config.secondaryName,\n    secondaryKeyword: config.secondaryKeyword,\n    narrativeProgressionActive: !!narrativeProgression.active,\n    narrativeProgressionReason: narrativeProgression.reason || 'none',\n    narrativeTimestampPrevious,\n    narrativeClockGuard,''',1)
    needle='''  if (/^B_/.test(String(pending.mode || '')) && pending.broadcastAirtimePrevious) {\n    const currentBroadcastTs = time.parseTimestamp(text);\n    const previousBroadcastTs = time.parseTimestamp(pending.broadcastAirtimePrevious);\n    if (currentBroadcastTs && previousBroadcastTs && currentBroadcastTs.minuteKey < previousBroadcastTs.minuteKey) {\n      issues.push(`Mode B 방송 송출 시각 역행: ${currentBroadcastTs.raw} < ${previousBroadcastTs.raw}`);\n    }\n  }\n\n  const knowledgeScan'''
    rep='''  if (/^B_/.test(String(pending.mode || '')) && pending.broadcastAirtimePrevious) {\n    const currentBroadcastTs = time.parseTimestamp(text);\n    const previousBroadcastTs = time.parseTimestamp(pending.broadcastAirtimePrevious);\n    if (currentBroadcastTs && previousBroadcastTs && currentBroadcastTs.minuteKey < previousBroadcastTs.minuteKey) {\n      issues.push(`Mode B 방송 송출 시각 역행: ${currentBroadcastTs.raw} < ${previousBroadcastTs.raw}`);\n    }\n  }\n  if (!/^B_/.test(String(pending.mode || '')) && pending.narrativeClockGuard && pending.narrativeTimestampPrevious) {\n    const currentNarrativeTs = time.parseTimestamp(text);\n    const previousNarrativeTs = time.parseTimestamp(pending.narrativeTimestampPrevious);\n    if (currentNarrativeTs && previousNarrativeTs && currentNarrativeTs.minuteKey < previousNarrativeTs.minuteKey) {\n      issues.push(`Narrative 현재 시각 역행: ${currentNarrativeTs.raw} < ${previousNarrativeTs.raw}`);\n    }\n  }\n\n  const knowledgeScan'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    s=s.replace('''  state.worldYear = null;\n  state.koreanAgeOffset = 0;\n  state.lastMode = 'A';''','''  state.worldYear = null;\n  state.koreanAgeOffset = 0;\n  state.narrativeTimestamp = null;\n  state.lastMode = 'A';''',1)
    s=s.replace('''    if (/^B_/.test(String(pending.mode || ''))) time.commitBroadcastAirtime(state, pending, cleaned);\n    if (pending.mode === 'B_END') {''','''    if (/^B_/.test(String(pending.mode || ''))) time.commitBroadcastAirtime(state, pending, cleaned);\n    else time.syncNarrativeTimestamp(state, cleaned, pending.mode);\n    if (pending.mode === 'B_END') {''',1)
    needle='''  if (/^B_/.test(String(p.mode || ''))) {\n    lines.push('mode_b_timestamp_semantics=broadcast_airtime');'''
    rep='''  if (!/^B_/.test(String(p.mode || '')) && p.narrativeProgressionActive) {\n    lines.push('timestamp_semantics=current_narrative_time');\n    lines.push('embedded_preview_flashback_or_event_time_does_not_replace_current_timestamp=1');\n    lines.push(`narrative_progression_hint=${p.narrativeProgressionReason || 'forward'}`);\n    if (p.narrativeClockGuard && p.narrativeTimestampPrevious) {\n      lines.push(`narrative_timestamp_previous=${p.narrativeTimestampPrevious}`);\n      lines.push('narrative_timestamp_must_not_precede_previous=1');\n    }\n  }\n  if (/^B_/.test(String(p.mode || ''))) {\n    lines.push('mode_b_timestamp_semantics=broadcast_airtime');'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    needle='''  time.applyWorldYear(state, time.timestampYear(finalText));\n  if (/^B_/.test(String(p.mode || ''))) {'''
    rep='''  time.applyWorldYear(state, time.timestampYear(finalText));\n  if (!/^B_/.test(String(p.mode || ''))) {\n    const narrativeCommit = time.commitNarrativeTimestamp(state, p, finalText);\n    if (narrativeCommit.reason === 'backward') {\n      state.lastNarrativeClockWarning = {\n        previous: narrativeCommit.previous || null,\n        rejected: narrativeCommit.timestamp || null,\n        outIndex: Number.isInteger(Number(outIndex)) ? Number(outIndex) : -1,\n        reason: p.narrativeProgressionReason || 'forward',\n      };\n    } else {\n      delete state.lastNarrativeClockWarning;\n    }\n  }\n  if (/^B_/.test(String(p.mode || ''))) {'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    needle='''  seedBroadcastAirtimeFromVisible(content) {\n    if (!this.current?.broadcastLocked || this.current.broadcastAirtime) return false;\n    if (!/^B_/.test(String(this.current.lastMode || ''))) return false;\n    const parsed = time.parseTimestamp(content);\n    if (!parsed) return false;\n    this.current.broadcastAirtime = parsed.raw;\n    if (!this.current.broadcastAirtimeStart) this.current.broadcastAirtimeStart = parsed.raw;\n    return true;\n  }\n\n  async reconcileEditedOutput'''
    rep='''  seedBroadcastAirtimeFromVisible(content) {\n    if (!this.current?.broadcastLocked || this.current.broadcastAirtime) return false;\n    if (!/^B_/.test(String(this.current.lastMode || ''))) return false;\n    const parsed = time.parseTimestamp(content);\n    if (!parsed) return false;\n    this.current.broadcastAirtime = parsed.raw;\n    if (!this.current.broadcastAirtimeStart) this.current.broadcastAirtimeStart = parsed.raw;\n    return true;\n  }\n\n  seedNarrativeTimestampFromVisible(content) {\n    if (!this.current || this.current.narrativeTimestamp) return false;\n    if (/^B_/.test(String(this.current.lastMode || ''))) return false;\n    const parsed = time.parseTimestamp(content);\n    if (!parsed) return false;\n    this.current.narrativeTimestamp = parsed.raw;\n    return true;\n  }\n\n  async reconcileEditedOutput'''
    assert needle in s, name
    s=s.replace(needle,rep,1)
    old='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      if (detail) { detail.path = airtimeSeeded ? 'same-fast+airtime-seed' : 'same-fast'; detail.compatibilitySource = 'canonical'; }\n      return { changed: false, reason: airtimeSeeded ? 'same-fast+airtime-seed' : 'same-fast' };'''
    new='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      const narrativeSeeded = this.seedNarrativeTimestampFromVisible(content);\n      const seeded = airtimeSeeded || narrativeSeeded;\n      if (detail) { detail.path = airtimeSeeded ? 'same-fast+airtime-seed' : (narrativeSeeded ? 'same-fast+narrative-seed' : 'same-fast'); detail.compatibilitySource = 'canonical'; }\n      return { changed: false, reason: seeded ? (airtimeSeeded ? 'same-fast+airtime-seed' : 'same-fast+narrative-seed') : 'same-fast' };'''
    assert old in s, name
    s=s.replace(old,new,1)
    old='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      if (detail) { detail.path = airtimeSeeded ? 'same-host-fast+airtime-seed' : 'same-host-fast'; detail.compatibilitySource = 'host-raw'; }\n      return { changed: false, reason: airtimeSeeded ? 'same-host-fast+airtime-seed' : 'same-host-fast' };'''
    new='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      const narrativeSeeded = this.seedNarrativeTimestampFromVisible(content);\n      const seeded = airtimeSeeded || narrativeSeeded;\n      if (detail) { detail.path = airtimeSeeded ? 'same-host-fast+airtime-seed' : (narrativeSeeded ? 'same-host-fast+narrative-seed' : 'same-host-fast'); detail.compatibilitySource = 'host-raw'; }\n      return { changed: false, reason: seeded ? (airtimeSeeded ? 'same-host-fast+airtime-seed' : 'same-host-fast+narrative-seed') : 'same-host-fast' };'''
    assert old in s, name
    s=s.replace(old,new,1)
    old='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      const hostMatch = savedOut.hostOutputFingerprint === actualFingerprint;\n      if (detail) {\n        detail.path = airtimeSeeded ? (hostMatch ? 'same-host-snapshot+airtime-seed' : 'same-snapshot+airtime-seed') : (hostMatch ? 'same-host-snapshot' : 'same-snapshot');\n        detail.compatibilitySource = hostMatch ? 'host-raw' : 'canonical';\n      }\n      return { changed: false, reason: airtimeSeeded ? (hostMatch ? 'same-host-snapshot+airtime-seed' : 'same-snapshot+airtime-seed') : (hostMatch ? 'same-host-snapshot' : 'same-snapshot') };'''
    new='''      const airtimeSeeded = this.seedBroadcastAirtimeFromVisible(content);\n      const narrativeSeeded = this.seedNarrativeTimestampFromVisible(content);\n      const hostMatch = savedOut.hostOutputFingerprint === actualFingerprint;\n      if (detail) {\n        detail.path = airtimeSeeded\n          ? (hostMatch ? 'same-host-snapshot+airtime-seed' : 'same-snapshot+airtime-seed')\n          : (narrativeSeeded ? (hostMatch ? 'same-host-snapshot+narrative-seed' : 'same-snapshot+narrative-seed') : (hostMatch ? 'same-host-snapshot' : 'same-snapshot'));\n        detail.compatibilitySource = hostMatch ? 'host-raw' : 'canonical';\n      }\n      return { changed: false, reason: detail?.path || (hostMatch ? 'same-host-snapshot' : 'same-snapshot') };'''
    assert old in s, name
    s=s.replace(old,new,1)
    s=s.replace('''      const clockChanged = time.applyWorldYear(baseline, time.timestampYear(kernel.stripControlTags(content)));\n      baseline.outputFingerprint = actualFingerprint;''','''      const clockChanged = time.applyWorldYear(baseline, time.timestampYear(kernel.stripControlTags(content)));\n      const narrativeClockChanged = time.syncNarrativeTimestamp(baseline, kernel.stripControlTags(content), baseline.lastMode);\n      baseline.outputFingerprint = actualFingerprint;''',1)
    s=s.replace("detail.path = repaired ? 'clock-repaired' : (clockChanged ? 'clock-synced' : 'baseline-created');","detail.path = repaired ? 'clock-repaired' : ((clockChanged || narrativeClockChanged) ? 'clock-synced' : 'baseline-created');",1)
    s=s.replace("return { changed: repaired || clockChanged, reason: repaired ? 'clock-repaired' : (clockChanged ? 'clock-synced' : 'baseline-created') };","return { changed: repaired || clockChanged || narrativeClockChanged, reason: repaired ? 'clock-repaired' : ((clockChanged || narrativeClockChanged) ? 'clock-synced' : 'baseline-created') };",1)
    s=s.replace('''      const clockChanged = time.applyWorldYear(same, time.timestampYear(kernel.stripControlTags(content)));\n      if (detail) detail.stateSyncMs += sessionElapsed(t);\n      if (repaired || clockChanged) {''','''      const clockChanged = time.applyWorldYear(same, time.timestampYear(kernel.stripControlTags(content)));\n      const narrativeClockChanged = time.syncNarrativeTimestamp(same, kernel.stripControlTags(content), same.lastMode);\n      if (detail) detail.stateSyncMs += sessionElapsed(t);\n      if (repaired || clockChanged || narrativeClockChanged) {''',1)
    s=s.replace("if (detail) detail.path = repaired ? 'clock-repaired' : (clockChanged ? 'clock-synced' : 'same');","if (detail) detail.path = repaired ? 'clock-repaired' : ((clockChanged || narrativeClockChanged) ? 'clock-synced' : 'same');",1)
    s=s.replace("return { changed: repaired || clockChanged, reason: repaired ? 'clock-repaired' : (clockChanged ? 'clock-synced' : 'same') };","return { changed: repaired || clockChanged || narrativeClockChanged, reason: repaired ? 'clock-repaired' : ((clockChanged || narrativeClockChanged) ? 'clock-synced' : 'same') };",1)
    s=s.replace('''<div><div class="k">World year</div><div class="v">${s?.worldYear ?? 'unknown'}</div></div>\n<div><div class="k">Warnings</div>''','''<div><div class="k">World year</div><div class="v">${s?.worldYear ?? 'unknown'}</div></div>\n<div><div class="k">Narrative anchor</div><div class="v">${escapeHtml(s?.narrativeTimestamp || 'unknown')}</div></div>\n<div><div class="k">Warnings</div>''',1)
    s=s.replace('''${(lastCore.diagnostics || []).length ? `<div class="card"><div class="k" style="margin-bottom:8px">Compatibility diagnostics</div><div>${lastCore.diagnostics.map((x) => `• ${escapeHtml(x)}`).join('<br>')}</div></div>` : ''}\n${lastHistoryRestore ?''','''${(lastCore.diagnostics || []).length ? `<div class="card"><div class="k" style="margin-bottom:8px">Compatibility diagnostics</div><div>${lastCore.diagnostics.map((x) => `• ${escapeHtml(x)}`).join('<br>')}</div></div>` : ''}\n${s?.lastNarrativeClockWarning ? `<div class="card"><div class="k" style="margin-bottom:8px">Narrative clock guard</div><div>REJECTED BACKWARD · ${escapeHtml(s.lastNarrativeClockWarning.rejected || 'unknown')}</div><div class="muted" style="margin-top:5px">previous ${escapeHtml(s.lastNarrativeClockWarning.previous || 'unknown')} · ${escapeHtml(s.lastNarrativeClockWarning.reason || 'forward')}</div></div>` : ''}\n${lastHistoryRestore ?''',1)
    s=s.replace('v0.62.18 Compact Diagnostics Panel · details collapsed by default · core behavior unchanged','v0.62.19 Narrative Clock Guard Phase 1 · relational forward guard · no calendar guessing',1)
    s=s.replace('[simcore/v0.62.18]', '[simcore/v0.62.19]')
    s=s.replace('SimCore v0.62.18', 'SimCore v0.62.19')
    p.write_text(s)
