from pathlib import Path

paths = [Path('plugins/simcore/latest.js'), Path('plugins/simcore/install.js')]

for p in paths:
    s = p.read_text(encoding='utf-8')
    if '//@version 0.62.23' not in s:
        raise SystemExit(f'{p}: expected v0.62.23 source')

    s = s.replace('//@version 0.62.23', '//@version 0.62.24', 1)
    s = s.replace('//@display-name SimCore v0.62.23 Request Lineage Probe', '//@display-name SimCore v0.62.24 Narrative Current-Time Floor', 1)

    release_marker = '// v0.62.23 Request Lineage Probe:'
    release_note = '''// v0.62.24 Narrative Current-Time Floor:\n// - Non-broadcast current narrative timestamps are monotonic even when a short A/C follow-up causes the model to emit an older source-event time\n// - If the first/current response timestamp is earlier than the prior narrative anchor, only that timestamp is clamped to the prior anchor; embedded/source-event times remain untouched\n// - State commit and manual-edit sync also refuse backward narrative-anchor movement as defense in depth\n// - One-time v1 -> v2 migration checks only the immediately preceding turn snapshot to recover an anchor already regressed by v0.62.23; no history rescan\n// - Mode B Broadcast Airtime Guard is unchanged; Request Lineage/Community/Reaction/Recurrence semantics are unchanged\n// - No auxiliary model, no new runtime-prompt tokens, and no new pluginStorage API call sites\n//\n'''
    if release_marker not in s:
        raise SystemExit(f'{p}: release marker missing')
    s = s.replace(release_marker, release_note + release_marker, 1)

    s = s.replace('const CLOCK_REPAIR_VERSION = 2;\n', 'const CLOCK_REPAIR_VERSION = 2;\nconst NARRATIVE_CLOCK_VERSION = 2;\n', 1)
    s = s.replace('    narrativeClockVersion: 1,\n', '    narrativeClockVersion: 2,\n', 1)

    old_time = '''function commitNarrativeTimestamp(state, pending, content) {\n  if (/^B_/.test(String(pending?.mode || ''))) return { changed: false, reason: 'broadcast', timestamp: null };\n  const parsed = parseTimestamp(content);\n  if (!parsed) return { changed: false, reason: 'missing-or-invalid', timestamp: null };\n  const current = parsed.raw;\n  const previous = pending?.narrativeTimestampPrevious || state.narrativeTimestamp || null;\n  if (pending?.narrativeClockGuard && previous) {\n    const cmp = compareTimestamps(current, previous);\n    if (cmp != null && cmp < 0) return { changed: false, reason: 'backward', timestamp: current, previous };\n  }\n  const changed = state.narrativeTimestamp !== current;\n  state.narrativeTimestamp = current;\n  return { changed, reason: 'committed', timestamp: current, previous };\n}\n\nfunction syncNarrativeTimestamp(state, content, mode) {\n  if (/^B_/.test(String(mode || ''))) return false;\n  const parsed = parseTimestamp(content);\n  if (!parsed) return false;\n  const changed = state.narrativeTimestamp !== parsed.raw;\n  state.narrativeTimestamp = parsed.raw;\n  return changed;\n}\n'''
    new_time = '''function enforceNarrativeCurrentTimeFloor(content, previous) {\n  const text = String(content || '');\n  const parsed = parseTimestamp(text);\n  if (!parsed) return { content: text, changed: false, reason: 'missing-or-invalid', observed: null, floor: previous || null };\n  if (!previous) return { content: text, changed: false, reason: 'no-floor', observed: parsed.raw, floor: null };\n  const cmp = compareTimestamps(parsed.raw, previous);\n  if (cmp == null || cmp >= 0) {\n    return { content: text, changed: false, reason: cmp === 0 ? 'same' : 'forward', observed: parsed.raw, floor: previous };\n  }\n  // The first canonical timestamp is current narrative time. Clamp only that token;\n  // later embedded/source-event timestamps are intentionally left untouched.\n  return {\n    content: text.replace(parsed.raw, previous),\n    changed: true,\n    reason: 'clamped-backward',\n    observed: parsed.raw,\n    floor: previous,\n  };\n}\n\nfunction commitNarrativeTimestamp(state, pending, content) {\n  if (/^B_/.test(String(pending?.mode || ''))) return { changed: false, reason: 'broadcast', timestamp: null };\n  const parsed = parseTimestamp(content);\n  if (!parsed) return { changed: false, reason: 'missing-or-invalid', timestamp: null };\n  const current = parsed.raw;\n  const previous = pending?.narrativeTimestampPrevious || state.narrativeTimestamp || null;\n  if (previous) {\n    const cmp = compareTimestamps(current, previous);\n    if (cmp != null && cmp < 0) return { changed: false, reason: 'backward', timestamp: current, previous };\n  }\n  const changed = state.narrativeTimestamp !== current;\n  state.narrativeTimestamp = current;\n  return { changed, reason: 'committed', timestamp: current, previous };\n}\n\nfunction syncNarrativeTimestamp(state, content, mode) {\n  if (/^B_/.test(String(mode || ''))) return false;\n  const parsed = parseTimestamp(content);\n  if (!parsed) return false;\n  const previous = state.narrativeTimestamp || null;\n  if (previous) {\n    const cmp = compareTimestamps(parsed.raw, previous);\n    if (cmp != null && cmp < 0) return false;\n  }\n  const changed = state.narrativeTimestamp !== parsed.raw;\n  state.narrativeTimestamp = parsed.raw;\n  return changed;\n}\n'''
    if old_time not in s:
        raise SystemExit(f'{p}: narrative time block missing')
    s = s.replace(old_time, new_time, 1)

    s = s.replace('  CLOCK_REPAIR_VERSION,\n  BROADCAST_TIMESTAMP_RE,', '  CLOCK_REPAIR_VERSION,\n  NARRATIVE_CLOCK_VERSION,\n  BROADCAST_TIMESTAMP_RE,', 1)
    s = s.replace('  narrativeProgressionHint,\n  commitNarrativeTimestamp,', '  narrativeProgressionHint,\n  enforceNarrativeCurrentTimeFloor,\n  commitNarrativeTimestamp,', 1)

    old_finalize = '''  time.applyWorldYear(state, time.timestampYear(finalText));\n  let narrativeClockProbe = null;\n  if (!/^B_/.test(String(p.mode || ''))) {\n    const narrativeCommit = time.commitNarrativeTimestamp(state, p, finalText);\n'''
    new_finalize = '''  let narrativeFloor = null;\n  if (!/^B_/.test(String(p.mode || ''))) {\n    narrativeFloor = time.enforceNarrativeCurrentTimeFloor(\n      finalText,\n      p.narrativeTimestampPrevious || state.narrativeTimestamp || null,\n    );\n    finalText = narrativeFloor.content;\n  }\n  time.applyWorldYear(state, time.timestampYear(finalText));\n  let narrativeClockProbe = null;\n  if (!/^B_/.test(String(p.mode || ''))) {\n    const narrativeCommit = time.commitNarrativeTimestamp(state, p, finalText);\n'''
    if old_finalize not in s:
        raise SystemExit(f'{p}: finalize insertion point missing')
    s = s.replace(old_finalize, new_finalize, 1)

    old_status = '''    let narrativeCommitStatus = 'UNKNOWN';\n    if (narrativeCommit.reason === 'backward') narrativeCommitStatus = 'REJECTED BACKWARD';\n    else if (narrativeCommit.reason === 'missing-or-invalid') narrativeCommitStatus = 'MISSING TIMESTAMP';\n'''
    new_status = '''    let narrativeCommitStatus = 'UNKNOWN';\n    if (narrativeFloor?.changed) narrativeCommitStatus = 'FLOOR CLAMPED';\n    else if (narrativeCommit.reason === 'backward') narrativeCommitStatus = 'REJECTED BACKWARD';\n    else if (narrativeCommit.reason === 'missing-or-invalid') narrativeCommitStatus = 'MISSING TIMESTAMP';\n'''
    if old_status not in s:
        raise SystemExit(f'{p}: narrative status block missing')
    s = s.replace(old_status, new_status, 1)

    old_probe = '''      previousAnchor: previousNarrative,\n      outputTimestamp: narrativeCommit.timestamp || null,\n      commitStatus: narrativeCommitStatus,\n      commitReason: narrativeCommit.reason || 'unknown',\n'''
    new_probe = '''      previousAnchor: previousNarrative,\n      observedTimestamp: narrativeFloor?.observed || narrativeCommit.timestamp || null,\n      outputTimestamp: narrativeCommit.timestamp || null,\n      floorApplied: !!narrativeFloor?.changed,\n      floorTimestamp: narrativeFloor?.floor || null,\n      commitStatus: narrativeCommitStatus,\n      commitReason: narrativeFloor?.changed ? 'clamped-backward' : (narrativeCommit.reason || 'unknown'),\n'''
    if old_probe not in s:
        raise SystemExit(f'{p}: narrative probe fields missing')
    s = s.replace(old_probe, new_probe, 1)

    old_warning = '''    if (narrativeCommit.reason === 'backward') {\n      state.lastNarrativeClockWarning = {\n        previous: narrativeCommit.previous || null,\n        rejected: narrativeCommit.timestamp || null,\n        outIndex: Number.isInteger(Number(outIndex)) ? Number(outIndex) : -1,\n        reason: p.narrativeProgressionReason || 'forward',\n      };\n    } else {\n      delete state.lastNarrativeClockWarning;\n    }\n'''
    new_warning = '''    if (narrativeFloor?.changed) {\n      state.lastNarrativeClockWarning = {\n        previous: narrativeFloor.floor || previousNarrative || null,\n        rejected: narrativeFloor.observed || null,\n        outIndex: Number.isInteger(Number(outIndex)) ? Number(outIndex) : -1,\n        reason: 'current-time-floor',\n        action: 'clamped',\n      };\n    } else if (narrativeCommit.reason === 'backward') {\n      state.lastNarrativeClockWarning = {\n        previous: narrativeCommit.previous || null,\n        rejected: narrativeCommit.timestamp || null,\n        outIndex: Number.isInteger(Number(outIndex)) ? Number(outIndex) : -1,\n        reason: p.narrativeProgressionReason || 'forward',\n        action: 'rejected',\n      };\n    } else {\n      delete state.lastNarrativeClockWarning;\n    }\n'''
    if old_warning not in s:
        raise SystemExit(f'{p}: narrative warning block missing')
    s = s.replace(old_warning, new_warning, 1)

    # One-time migration: recover only from the immediately preceding turn snapshot, never full history.
    constructor_old = '''    this.communityAliasRepairStats = null;\n    this.templateRecurrenceBootstrapStats = null;\n  }\n\n  async init(latestOutIndex = -1, mirrorRaw = null, latestOutputFingerprint = null) {\n'''
    constructor_new = '''    this.communityAliasRepairStats = null;\n    this.templateRecurrenceBootstrapStats = null;\n    this.narrativeClockMigrationStats = null;\n  }\n\n  async migrateNarrativeCurrentTimeFloorIfNeeded(latestOutIndex = -1) {\n    const state = kernel.reconcileState(this.current || kernel.initialState());\n    const fromVersion = Math.max(1, Number(state.narrativeClockVersion || 1));\n    if (fromVersion >= time.NARRATIVE_CLOCK_VERSION) {\n      this.current = state;\n      return { changed: false, skipped: true, fromVersion, toVersion: fromVersion };\n    }\n\n    const before = state.narrativeTimestamp || null;\n    let candidate = null;\n    let source = 'none';\n    const sendIndex = Number.isInteger(Number(latestOutIndex)) && Number(latestOutIndex) > 0\n      ? Number(latestOutIndex) - 1\n      : -1;\n    if (sendIndex >= 0) {\n      const turn = await this.store.loadTurn(sendIndex);\n      const choices = [\n        ['send', turn?.send?.narrativeTimestamp || null],\n        ['pre', turn?.pre?.narrativeTimestamp || null],\n      ];\n      for (const [label, ts] of choices) {\n        if (!time.parseTimestamp(ts)) continue;\n        if (!candidate) { candidate = ts; source = label; continue; }\n        const cmp = time.compareTimestamps(ts, candidate);\n        if (cmp != null && cmp > 0) { candidate = ts; source = label; }\n      }\n    }\n\n    let changed = false;\n    if (candidate) {\n      const cmp = before ? time.compareTimestamps(candidate, before) : 1;\n      if (!before || (cmp != null && cmp > 0)) {\n        state.narrativeTimestamp = candidate;\n        changed = true;\n      }\n    }\n    state.narrativeClockVersion = time.NARRATIVE_CLOCK_VERSION;\n    this.current = state;\n    this.narrativeClockMigrationStats = {\n      changed,\n      fromVersion,\n      toVersion: time.NARRATIVE_CLOCK_VERSION,\n      sendIndex,\n      before,\n      candidate,\n      after: state.narrativeTimestamp || null,\n      source,\n    };\n    return this.narrativeClockMigrationStats;\n  }\n\n  async init(latestOutIndex = -1, mirrorRaw = null, latestOutputFingerprint = null) {\n'''
    if constructor_old not in s:
        raise SystemExit(f'{p}: session constructor marker missing')
    s = s.replace(constructor_old, constructor_new, 1)

    # Run the migration before each existing-state init return. It is a no-op after v2.
    s = s.replace('''      this.trustedHostOutputFingerprint = mirrorHostFingerprint;\n      return this.current;\n''', '''      this.trustedHostOutputFingerprint = mirrorHostFingerprint;\n      await this.migrateNarrativeCurrentTimeFloorIfNeeded(latestOutIndex);\n      return this.current;\n''', 1)
    s = s.replace('''        this.trustedHostOutputFingerprint = (!this.loadedFromLegacySnapshot\n          && Number(this.current.clockRepairVersion || 0) >= time.CLOCK_REPAIR_VERSION)\n          ? (this.current.hostOutputFingerprint || null) : null;\n        return this.current;\n''', '''        this.trustedHostOutputFingerprint = (!this.loadedFromLegacySnapshot\n          && Number(this.current.clockRepairVersion || 0) >= time.CLOCK_REPAIR_VERSION)\n          ? (this.current.hostOutputFingerprint || null) : null;\n        await this.migrateNarrativeCurrentTimeFloorIfNeeded(found.index);\n        return this.current;\n''', 1)
    # Same block appears again for mirror fallback; replace the next remaining occurrence.
    mirror_block = '''        this.trustedHostOutputFingerprint = (!this.loadedFromLegacySnapshot\n          && Number(this.current.clockRepairVersion || 0) >= time.CLOCK_REPAIR_VERSION)\n          ? (this.current.hostOutputFingerprint || null) : null;\n        return this.current;\n'''
    mirror_repl = '''        this.trustedHostOutputFingerprint = (!this.loadedFromLegacySnapshot\n          && Number(this.current.clockRepairVersion || 0) >= time.CLOCK_REPAIR_VERSION)\n          ? (this.current.hostOutputFingerprint || null) : null;\n        await this.migrateNarrativeCurrentTimeFloorIfNeeded(latestOutIndex);\n        return this.current;\n'''
    if mirror_block not in s:
        raise SystemExit(f'{p}: mirror init return marker missing')
    s = s.replace(mirror_block, mirror_repl, 1)

    # Panel/runtime visibility only; no prompt change.
    s = s.replace('⚙️ SimCore v0.62.23 <button id="close">', '⚙️ SimCore v0.62.24 <button id="close">', 1)
    s = s.replace('''<div class="metric"><div class="k">Narrative guard</div><div class="v">${narrativeGuardLabel}</div></div>\n<div class="metric"><div class="k">Mode transition</div>''', '''<div class="metric"><div class="k">Narrative guard</div><div class="v">${narrativeGuardLabel}</div></div>\n<div class="metric"><div class="k">Current-time floor</div><div class="v">${narrativeProbe?.floorApplied ? 'CLAMPED' : 'ON'}</div></div>\n<div class="metric"><div class="k">Mode transition</div>''', 1)
    old_probe_card = '''${narrativeProbe ? `<div class="card"><div class="k" style="margin-bottom:8px">Narrative clock probe (runtime)</div><div>${escapeHtml(narrativeProbe.commitStatus || 'UNKNOWN')} · ${escapeHtml(narrativeTransition)} · guard ${narrativeProbe.guardActive ? 'ON' : 'OFF'}</div><div class="muted" style="margin-top:5px">trigger ${escapeHtml(narrativeProbe.trigger || 'none')} · previous ${escapeHtml(narrativeProbe.previousAnchor || 'unknown')} · output ${escapeHtml(narrativeProbe.outputTimestamp || 'pending')}</div></div>` : ''}\n${s?.lastNarrativeClockWarning ? `<div class="card"><div class="k" style="margin-bottom:8px">Narrative clock guard</div><div>REJECTED BACKWARD · ${escapeHtml(s.lastNarrativeClockWarning.rejected || 'unknown')}</div><div class="muted" style="margin-top:5px">previous ${escapeHtml(s.lastNarrativeClockWarning.previous || 'unknown')} · ${escapeHtml(s.lastNarrativeClockWarning.reason || 'forward')}</div></div>` : ''}\n'''
    new_probe_card = '''${narrativeProbe ? `<div class="card"><div class="k" style="margin-bottom:8px">Narrative clock probe (runtime)</div><div>${escapeHtml(narrativeProbe.commitStatus || 'UNKNOWN')} · ${escapeHtml(narrativeTransition)} · guard ${narrativeProbe.guardActive ? 'ON' : 'OFF'}</div><div class="muted" style="margin-top:5px">trigger ${escapeHtml(narrativeProbe.trigger || 'none')} · previous ${escapeHtml(narrativeProbe.previousAnchor || 'unknown')} · observed ${escapeHtml(narrativeProbe.observedTimestamp || 'pending')} · committed ${escapeHtml(narrativeProbe.outputTimestamp || 'pending')}</div></div>` : ''}\n${s?.lastNarrativeClockWarning ? `<div class="card"><div class="k" style="margin-bottom:8px">Narrative current-time floor</div><div>${s.lastNarrativeClockWarning.action === 'clamped' ? 'FLOOR CLAMPED' : 'REJECTED BACKWARD'} · ${escapeHtml(s.lastNarrativeClockWarning.rejected || 'unknown')}</div><div class="muted" style="margin-top:5px">floor ${escapeHtml(s.lastNarrativeClockWarning.previous || 'unknown')} · ${escapeHtml(s.lastNarrativeClockWarning.reason || 'forward')}</div></div>` : ''}\n'''
    if old_probe_card not in s:
        raise SystemExit(f'{p}: narrative panel card missing')
    s = s.replace(old_probe_card, new_probe_card, 1)
    s = s.replace('v0.62.20 Narrative Clock Diagnostics · runtime probe only · behavior unchanged', 'v0.62.24 Narrative Current-Time Floor · A/C current timestamp monotonic · B airtime unchanged', 1)

    s = s.replace('[simcore/v0.62.23]', '[simcore/v0.62.24]')

    p.write_text(s, encoding='utf-8')

print('patched v0.62.24')
