export const registry = Object.freeze([
  { id: 'representation-fast', module: './suites/representation-fast.test.mjs', fixtureDir: 'representation-fast', coverage: 'HYBRID_TRANSITIONAL', required: true, goldenGate: true },
  { id: 'genuine-edit', module: './suites/genuine-edit.test.mjs', fixtureDir: 'genuine-edit', coverage: 'HYBRID_TRANSITIONAL', required: true, goldenGate: true },
  { id: 'community-reaction', module: './suites/community-reaction.test.mjs', fixtureDir: 'community-reaction', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'community-parent-local-alias', module: './suites/community-parent-local-alias-v06800.test.mjs', fixtureDir: 'community-parent-local-alias', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v06800', module: './suites/builder-v06800.test.mjs', fixtureDir: 'builder-v06800', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v06900', module: './suites/builder-v06900.test.mjs', fixtureDir: 'builder-v06900', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v06901', module: './suites/builder-v06901.test.mjs', fixtureDir: 'builder-v06901', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v06902', module: './suites/builder-v06902.test.mjs', fixtureDir: 'builder-v06902', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v07000', module: './suites/builder-v07000.test.mjs', fixtureDir: 'builder-v07000', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'builder-v07001', module: './suites/builder-v07001.test.mjs', fixtureDir: 'builder-v07001', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'summary-scope', module: './suites/summary-scope.test.mjs', fixtureDir: 'summary-scope', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'narrative-clock', module: './suites/narrative-clock.test.mjs', fixtureDir: 'narrative-clock', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'frame', module: './suites/frame.test.mjs', fixtureDir: 'frame', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'broadcast-closure', module: './suites/broadcast-closure.test.mjs', fixtureDir: 'broadcast-closure', coverage: 'HYBRID_TRANSITIONAL', required: true, goldenGate: true },
  { id: 'diagnostic-copy', module: './suites/diagnostic-copy.test.mjs', fixtureDir: 'diagnostic-copy', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'reload-cache-continuity', module: './suites/release-validation-active-r2-9.mjs', fixtureDir: 'reload-cache-continuity', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'operator-release-card', module: './suites/release-validation-active-r2-9.mjs', fixtureDir: 'operator-release-card', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'host-local-telemetry', module: './suites/release-validation-active-r2-9.mjs', fixtureDir: 'host-local-telemetry', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'bounded-telemetry-capsule', module: './suites/release-validation-active-r2-9.mjs', fixtureDir: 'bounded-telemetry-capsule', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'preflight-compression', module: './suites/preflight-compression.test.mjs', fixtureDir: 'preflight-compression', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'candidate-materialize', module: './suites/candidate-materialize.test.mjs', fixtureDir: 'candidate-materialize', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'candidate-receipt', module: './suites/candidate-receipt.test.mjs', fixtureDir: 'candidate-receipt', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-spec-contract', module: './suites/release-spec-contract.test.mjs', fixtureDir: 'release-spec-contract', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'closure-integrity', module: './suites/closure-integrity.test.mjs', fixtureDir: 'closure-integrity', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'stability-seal', module: './suites/stability-seal.test.mjs', fixtureDir: 'stability-seal', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-approval', module: './suites/release-approval.test.mjs', fixtureDir: 'release-approval', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-system-r2-6', module: './suites/release-system-r2-6.test.mjs', fixtureDir: 'release-system-r2-6', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-system-r2-7', module: './suites/release-system-r2-7.test.mjs', fixtureDir: 'release-system-r2-7', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-system-r2-7-status-projection', module: './suites/release-system-r2-7-status-projection.test.mjs', fixtureDir: 'release-system-r2-7-status-projection', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-system-r2-8-terminal-convergence', module: './suites/release-system-r2-8-terminal-convergence.test.mjs', fixtureDir: 'release-system-r2-8-terminal-convergence', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'release-system-r2-9-validation-contract-projection', module: './suites/release-system-r2-9-validation-contract-projection.test.mjs', fixtureDir: 'release-system-r2-9-validation-contract-projection', coverage: 'EXECUTABLE', required: true, goldenGate: true },
  { id: 'architecture-contract-select-v06900', module: './suites/architecture-contract-select-v06900.test.mjs', fixtureDir: 'architecture-contract-select-v06900', coverage: 'EXECUTABLE', required: true, goldenGate: true }
]);

export const packAliases = Object.freeze({
  'batch-a': registry.map((row) => row.id),
  all: registry.map((row) => row.id),
});
