#!/usr/bin/env python3
import json
import os
from pathlib import Path

VERSION = '0.63.56'
RELEASE_NAME = 'M2-1 Recovery Boundary Split'
PRIORITY = '2M_MAJOR_M2_1_LIVE_VALIDATION'

release_commit = os.environ['RELEASE_COMMIT']
release_blob = os.environ['RELEASE_BLOB']


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'{label}: expected text not found')
    return text.replace(old, new, 1)


def add_unique(seq, value):
    if value not in seq:
        seq.append(value)

# Manifest: existing generic sync has already set release identity.
manifest_path = Path('product-manifest.json')
manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
if manifest.get('production_version') != VERSION:
    raise SystemExit(f'expected production {VERSION}, got {manifest.get("production_version")}')
manifest['current_priority'] = PRIORITY
manifest['validation_status'] = 'PENDING_REAL_LONG_CHAT'
manifest['major_update_milestone'] = '2.0M'
manifest['major_update_phase'] = 'M2'
manifest['major_update_checkpoint'] = 'M2-1'
manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

# Contracts v2 now describes the physical M2-1 production graph.
contract_path = Path('config/simcore-architecture-v2.json')
contract = json.loads(contract_path.read_text(encoding='utf-8'))
contract['production_baseline'] = {
    'version': VERSION,
    'release_name': RELEASE_NAME,
    'release_commit': release_commit,
    'release_blob': release_blob,
}
major = contract['major_update']
major['phase'] = 'M2'
major['checkpoint'] = 'M2-1'
major['status'] = 'M2_1_RELEASED_PENDING_LIVE_VALIDATION'
major['runtime_refactor_authorized'] = True
major['m2_1_release'] = {
    'version': VERSION,
    'release_commit': release_commit,
    'release_blob': release_blob,
    'scope': 'mechanical recovery boundary split only',
    'live_validation': 'PENDING',
}

recovery = contract['modules']['recovery']
recovery['status'] = 'm2_1_compatibility_facade'
recovery['owns'] = 'compatibility facade over output-compat and bootstrap-migration during staged M2 migration'
for dep in ['output-compat', 'bootstrap-migration']:
    add_unique(recovery['allowed_dependencies'], dep)

output_compat = contract['modules']['output-compat']
output_compat['physical'] = 'required'
output_compat['status'] = 'm2_1_physical_pending_live_validation'

bootstrap = contract['modules']['bootstrap-migration']
bootstrap['physical'] = 'required'
bootstrap['status'] = 'm2_1_physical_pending_live_validation'
add_unique(bootstrap['allowed_dependencies'], 'output-compat')

completed = contract['transition_policy'].setdefault('completed_checkpoints', [])
add_unique(completed, 'M2-1: Recovery mechanically split into output-compat + bootstrap-migration behind compatibility facade')
contract_path.write_text(json.dumps(contract, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

# Durable sync script must not roll v0.63.56 priority back later.
sync_path = Path('scripts/simcore-sync-memory.py')
sync = sync_path.read_text(encoding='utf-8')
sync = replace_once(
    sync,
    "    '0.63.55': '2M_MAJOR_M2_MECHANICAL_BOUNDARY_REFACTOR',",
    "    '0.63.55': '2M_MAJOR_M2_MECHANICAL_BOUNDARY_REFACTOR',\n    '0.63.56': '2M_MAJOR_M2_1_LIVE_VALIDATION',",
    'sync priority map',
)
sync_path.write_text(sync, encoding='utf-8')

# Current development memory: snapshot was generated by generic sync; align priority and add checkpoint record.
dev_path = Path('docs/CURRENT_DEVELOPMENT.md')
dev = dev_path.read_text(encoding='utf-8')
dev = dev.replace('- Primary optimization target: `2M_MAJOR_M2_MECHANICAL_BOUNDARY_REFACTOR`', f'- Primary optimization target: `{PRIORITY}`', 1)
checkpoint = '''\n## M2-1 — Recovery Boundary Split\n\nStatus: **PRODUCTION · PENDING REAL LONG-CHAT VALIDATION**\n\n`v0.63.56` is the first physical code-movement checkpoint of the 2.0M Major. It is intentionally mechanical:\n\n```text\nold Recovery\n├─ output envelope / tail / Fresh-confirmation candidate logic\n├─ history bootstrap\n└─ legacy migration/repair\n\nnew\n├─ output-compat\n├─ bootstrap-migration\n└─ recovery compatibility facade\n```\n\nFrozen behavior target:\n\n- all moved function bodies are preserved verbatim by the release patch;\n- Session/runtime callers still import `recovery`, so orchestration order is unchanged;\n- `REPRESENTATION_FAST_RECONCILED` remains the validated v0.63.55 request-side control;\n- genuine user edits must remain `USER_EDIT_CANDIDATE -> MANUAL_EDIT_REBUILT`;\n- Structure remains judge-only; History remains `OBSERVE_ONLY`; provider cache remains `UNVERIFIED`;\n- storage/API/network/timer surfaces and persistent state schema are unchanged.\n\nLive validation should first prove ordinary A/C/B turns remain stable and then, when naturally available, reconfirm the representation fast path / genuine-edit controls. Do not mix storage-latency optimization into this checkpoint.\n'''
if '## M2-1 — Recovery Boundary Split' not in dev:
    marker = '# 2. Current Validation Release\n'
    if marker not in dev:
        raise SystemExit('CURRENT_DEVELOPMENT section marker missing')
    dev = dev.replace(marker, marker + checkpoint + '\n', 1)
dev_path.write_text(dev, encoding='utf-8')

contracts_path = Path('docs/SIMCORE_CONTRACTS_V2.md')
contracts = contracts_path.read_text(encoding='utf-8')
if '## 15. M2-1 Physical Checkpoint — Recovery Boundary Split' not in contracts:
    contracts += '''\n\n---\n\n## 15. M2-1 Physical Checkpoint — Recovery Boundary Split\n\nProduction `v0.63.56` materializes the first two planned application modules:\n\n```text\noutput-compat\nbootstrap-migration\n```\n\nThe old `recovery` module remains temporarily as a compatibility facade exporting the exact same public API. Existing Session/runtime callers therefore do not move in M2-1. The release patch moves existing function definitions without changing their bodies and validates the resulting source against Contracts v2.\n\nM2-1 does **not** yet move Representation Fast Reconcile or the manual-edit decision tree. Those remain in their v0.63.55 locations and are frozen regression controls for the next checkpoint.\n\nExit condition for M2-1: real long-chat behavior remains stable with no new warning/rebuild class attributable to the split. Only after that evidence may M2 continue to Representation/Edit ownership movement.\n'''
contracts_path.write_text(contracts, encoding='utf-8')

print('SimCore v0.63.56 M2-1 durable memory updated.')
