#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const SHA40=/^[0-9a-f]{40}$/;
const sha256=b=>crypto.createHash('sha256').update(b).digest('hex');
const gitBlob=b=>crypto.createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b])).digest('hex');
function fail(code,msg){const e=new Error(msg);e.code=code;throw e;}
function parse(argv){const o={};for(let i=0;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||!argv[i+1])fail('INVOCATION_ERROR','key/value args required');o[argv[i].slice(2)]=argv[i+1];}for(const k of ['root','manifest','production-identity','report'])if(!o[k])fail('INVOCATION_ERROR',`--${k} required`);return o;}
function under(root,rel){if(path.isAbsolute(rel))fail('PATH_OUTSIDE_ROOT',rel);const p=path.resolve(root,rel);if(p!==root&&!p.startsWith(root+path.sep))fail('PATH_OUTSIDE_ROOT',rel);return p;}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8'));}
function renderDev(m){return [`<!-- SIMCORE_SYNC:PRODUCTION_SNAPSHOT:BEGIN -->`,'## Current Production Snapshot','',`- Product: ${m.product}`,`- Version: \`${m.production_version}\``,`- Release: \`${m.release_name}\``,`- Release branch: \`${m.release_branch}\``,`- Release commit: \`${m.release_commit}\``,`- Release blob: \`${m.release_blob}\``,`- Declared validation status: \`${m.validation_status}\``,`- Major update milestone: \`${m.major_update_milestone}\``,`- Major update phase: \`${m.major_update_phase}\``,`- Major update checkpoint: \`${m.major_update_checkpoint}\``,'','This block is machine-managed from verified declared release state. It does not determine the immediate next action.','<!-- SIMCORE_SYNC:PRODUCTION_SNAPSHOT:END -->'].join('\n');}
function renderGuide(m){return ['<!-- SIMCORE_SYNC:PRODUCTION_BASELINE:BEGIN -->','```text',`SimCore v${m.production_version} — ${m.release_name}`,`Release commit: ${m.release_commit}`,'```','<!-- SIMCORE_SYNC:PRODUCTION_BASELINE:END -->'].join('\n');}
function verify(root,m,id){if(id.schemaVersion!==1||id.product!=='SimCore'||id.resolvedBranch!==m.release_branch||id.resolvedCommit!==m.release_commit)fail('SOURCE_IDENTITY_DRIFT','commit/branch mismatch');for(const k of ['latest','install'])if(!id[k]||!SHA40.test(id[k].blob||''))fail('PRODUCTION_IDENTITY_RECORD_INVALID',k);const a=fs.readFileSync(under(root,id.latest.path)),b=fs.readFileSync(under(root,id.install.path));const ab=gitBlob(a),bb=gitBlob(b);if(ab!==id.latest.blob||bb!==id.install.blob||ab!==m.release_blob||ab!==bb||!a.equals(b))fail('SOURCE_IDENTITY_DRIFT','blob mismatch');const text=a.toString('utf8');const v=text.match(/^\/\/@version\s+([^\r\n]+)$/m)?.[1]?.trim();const rn=text.match(new RegExp(`^// v${m.production_version.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s+(.+?):\\s*$`,'m'))?.[1]?.trim();if(v!==m.production_version||rn!==m.release_name)fail('SOURCE_IDENTITY_DRIFT','source markers mismatch');return {commit:id.resolvedCommit,blob:ab,sha256:sha256(a)};}
function replaceDev(root,m){const p=under(root,'docs/CURRENT_DEVELOPMENT.md'),old=fs.readFileSync(p,'utf8');const lb='<!-- SIMCORE_PRODUCTION_SNAPSHOT:BEGIN -->',le='<!-- SIMCORE_PRODUCTION_SNAPSHOT:END -->',cb='<!-- SIMCORE_SYNC:PRODUCTION_SNAPSHOT:BEGIN -->';if((old.split(lb).length-1)!==1||(old.split(le).length-1)!==1||old.includes(cb))fail('MIGRATION_SOURCE_AMBIGUOUS','CURRENT_DEVELOPMENT');const a=old.indexOf(lb),b=old.indexOf(le)+le.length;const prefix=old.slice(0,a),suffix=old.slice(b),next=prefix+renderDev(m)+suffix;fs.writeFileSync(p,next,'utf8');return {path:'docs/CURRENT_DEVELOPMENT.md',prefixBefore:sha256(Buffer.from(prefix)),prefixAfter:sha256(Buffer.from(next.slice(0,a))),suffixBefore:sha256(Buffer.from(suffix)),suffixAfter:sha256(Buffer.from(next.slice(prefix.length+renderDev(m).length))),beforeHash:sha256(Buffer.from(old)),afterHash:sha256(Buffer.from(next))};}
function replaceGuide(root,m){const p=under(root,'docs/SIMCORE_GUIDELINES.md'),old=fs.readFileSync(p,'utf8');if(old.includes('<!-- SIMCORE_SYNC:PRODUCTION_BASELINE:BEGIN -->'))fail('MIGRATION_SOURCE_AMBIGUOUS','Guidelines already enrolled');const sectionStart=old.indexOf('## 44. Current Production Baseline');if(sectionStart<0)fail('MIGRATION_SOURCE_AMBIGUOUS','Guidelines heading missing');const nextHeading=old.indexOf('\n## 45.',sectionStart);const end=nextHeading<0?old.length:nextHeading;const section=old.slice(sectionStart,end);const matches=[...section.matchAll(/```text\nSimCore v[^\n]+(?:\nRelease commit: [^\n]+)?\n```/g)];if(matches.length!==1)fail('MIGRATION_SOURCE_AMBIGUOUS',`Guidelines baseline count=${matches.length}`);const localA=matches[0].index,localB=localA+matches[0][0].length,a=sectionStart+localA,b=sectionStart+localB;const prefix=old.slice(0,a),suffix=old.slice(b),next=prefix+renderGuide(m)+suffix;fs.writeFileSync(p,next,'utf8');return {path:'docs/SIMCORE_GUIDELINES.md',prefixBefore:sha256(Buffer.from(prefix)),prefixAfter:sha256(Buffer.from(next.slice(0,a))),suffixBefore:sha256(Buffer.from(suffix)),suffixAfter:sha256(Buffer.from(next.slice(prefix.length+renderGuide(m).length))),beforeHash:sha256(Buffer.from(old)),afterHash:sha256(Buffer.from(next))};}
try{const a=parse(process.argv.slice(2)),root=path.resolve(a.root),m=readJson(under(root,a.manifest)),id=readJson(under(root,a['production-identity']));const source=verify(root,m,id);const changes=[replaceDev(root,m),replaceGuide(root,m)];for(const c of changes)if(c.prefixBefore!==c.prefixAfter||c.suffixBefore!==c.suffixAfter)fail('UNMANAGED_BYTES_MUTATED',c.path);const report={schemaVersion:1,migration:'RS2-2C',status:'PASS',source,changes};fs.writeFileSync(path.resolve(a.report),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}catch(e){console.error(`${e.code||'MIGRATION_ERROR'}: ${e.message}`);process.exitCode=2;}
