from pathlib import Path

p = Path('plugins/simcore/latest.js')
s = p.read_text()


def rep(old, new, label):
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 match, got {n}')
    s = s.replace(old, new, 1)


rep('//@version 0.63.42', '//@version 0.63.43', 'metadata version')
rep("const SIMCORE_RUNTIME_VERSION = '0.63.42';", "const SIMCORE_RUNTIME_VERSION = '0.63.43';", 'runtime version')
rep('// v0.63.42 Cache Integrity & Cost Stabilization:', '''// v0.63.43 Broadcast End Authority & Runtime Identity Precision:\n// - Makes episode/broadcast completion an explicit lifecycle authority: an open broadcast denies end narration across broadcast prose, COMMUNITY and Knowledge until the current lifecycle is B_END\n// - B_END is the only active-broadcast mode that authorizes episode-end narration; local scene/segment/mission/vote/player-departure completion does not imply broadcast completion\n// - Keeps the guard state-driven rather than phrase-blacklist-driven: SimCore communicates lifecycle authority but does not semantically parse or rewrite narrative text\n// - Replaces runtime identity's regex tier guess on the live path with compiler-native stable/slow/volatile source tiers while preserving the exact runtime prompt byte order and TAIL_AFTER_CURRENT_USER placement\n// - Keeps v0.63.42 cache topology/trajectory/exposure, v0.63.41 Continuity, v0.63.40 Evidence, Deferred Mirror acceptance, provider-cache policy and storage/API/timer/network surfaces frozen\n//\n// v0.63.42 Cache Integrity & Cost Stabilization:''', 'release notes')
rep('const PROMPT_COMPILER_VERSION = 1;', 'const PROMPT_COMPILER_VERSION = 2;', 'prompt compiler version')

rep('''function compileModeState(s, p, communityExpected) {\n  return [\n    `mode=${p.mode}`,\n    `broadcast_locked=${s.broadcastLocked ? 1 : 0}`,\n    `community_blocks_expected=${communityExpected}`,\n  ];\n}\n\nfunction compileConditionalGuidance(s, p, communityExpected) {\n  const lines = [];''', '''function compileModeState(s, p, communityExpected) {\n  return [\n    `mode=${p.mode}`,\n    `broadcast_locked=${s.broadcastLocked ? 1 : 0}`,\n    `community_blocks_expected=${communityExpected}`,\n  ];\n}\n\nfunction broadcastEndAuthority(s, p) {\n  const mode = String(p?.mode || '');\n  if (mode === 'B_END') {\n    return Object.freeze({ session: 'ENDING', authority: 'ALLOWED', reason: 'explicit-b-end' });\n  }\n  if (s?.broadcastLocked) {\n    return Object.freeze({\n      session: 'OPEN',\n      authority: 'DENIED',\n      reason: /^B_/.test(mode) ? 'active-broadcast' : 'inherited-open-broadcast',\n    });\n  }\n  return Object.freeze({ session: 'CLOSED', authority: 'NOT_APPLICABLE', reason: 'no-open-broadcast' });\n}\n\nfunction compileConditionalGuidance(s, p, communityExpected) {\n  const lines = [];\n  const endAuthority = broadcastEndAuthority(s, p);\n  if (endAuthority.authority === 'DENIED') {\n    lines.push('broadcast_session_state=OPEN');\n    lines.push('broadcast_end_authority=DENIED');\n    lines.push('episode_end_authority=DENIED');\n    lines.push('broadcast_end_requires_explicit_B_END_lifecycle=1');\n    lines.push('do_not_narrate_or_imply_broadcast_or_episode_end=1');\n    lines.push('scene_segment_mission_vote_or_player_departure_completion_does_not_authorize_episode_end=1');\n    lines.push('broadcast_end_boundary_applies_to=broadcast_prose+COMMUNITY+Knowledge');\n  } else if (endAuthority.authority === 'ALLOWED') {\n    lines.push('broadcast_session_state=ENDING');\n    lines.push('broadcast_end_authority=ALLOWED');\n    lines.push('episode_end_authority=ALLOWED');\n    lines.push('broadcast_end_basis=explicit_B_END_lifecycle');\n  }''', 'broadcast end authority')

rep('''function compileRuntimePrompt(state) {\n  const s = kernel.reconcileState(state);\n  const p = s.pending;\n  if (!p?.active) return '';\n  const communityExpected = lifecycle.expectedCommunityBlocks(p.mode);\n  const tiers = [\n    compileStableContract(),\n    compileSlowState(s, p),\n    compileModeState(s, p, communityExpected),\n    compileConditionalGuidance(s, p, communityExpected),\n    compileHotState(s, communityExpected),\n    compileFooter(communityExpected),\n  ];\n  return tiers.flat().join('\\n');\n}\n\nfunction renderRuntimePrompt(state) {\n  return compileRuntimePrompt(state);\n}\n\nmodule.exports = { PROMPT_COMPILER_VERSION, compileRuntimePrompt, renderRuntimePrompt };''', '''function compileRuntimePromptParts(state) {\n  const s = kernel.reconcileState(state);\n  const p = s.pending;\n  if (!p?.active) {\n    return Object.freeze({\n      text: '',\n      identityTiers: Object.freeze({ stable: '', slow: '', volatile: '' }),\n      endAuthority: Object.freeze({ session: 'CLOSED', authority: 'NOT_APPLICABLE', reason: 'inactive' }),\n    });\n  }\n  const communityExpected = lifecycle.expectedCommunityBlocks(p.mode);\n  const stableLines = compileStableContract();\n  const slowLines = compileSlowState(s, p);\n  const modeLines = compileModeState(s, p, communityExpected);\n  const conditionalLines = compileConditionalGuidance(s, p, communityExpected);\n  const hotLines = compileHotState(s, communityExpected);\n  const footerLines = compileFooter(communityExpected);\n  const volatileLines = [modeLines, conditionalLines, hotLines, footerLines].flat();\n  const text = [stableLines, slowLines, modeLines, conditionalLines, hotLines, footerLines].flat().join('\\n');\n  return Object.freeze({\n    text,\n    identityTiers: Object.freeze({\n      stable: stableLines.join('\\n'),\n      slow: slowLines.join('\\n'),\n      volatile: volatileLines.join('\\n'),\n    }),\n    endAuthority: broadcastEndAuthority(s, p),\n  });\n}\n\nfunction compileRuntimePrompt(state) {\n  return compileRuntimePromptParts(state).text;\n}\n\nfunction renderRuntimePrompt(state) {\n  return compileRuntimePrompt(state);\n}\n\nmodule.exports = { PROMPT_COMPILER_VERSION, broadcastEndAuthority, compileRuntimePromptParts, compileRuntimePrompt, renderRuntimePrompt };''', 'compiler native tiers')

rep('''const renderRuntimePrompt = prompt.renderRuntimePrompt;''', '''const renderRuntimePrompt = prompt.renderRuntimePrompt;\nconst compileRuntimePromptParts = prompt.compileRuntimePromptParts;''', 'session prompt parts binding')
rep('''    t = sessionNow();\n    const promptBlock = renderRuntimePrompt(state);\n    if (detail) detail.runtimeRenderMs = sessionElapsed(t);\n    return { state, promptBlock, active: !!state.pending?.active };''', '''    t = sessionNow();\n    const promptCompiled = compileRuntimePromptParts(state);\n    const promptBlock = promptCompiled.text;\n    if (detail) detail.runtimeRenderMs = sessionElapsed(t);\n    return {\n      state,\n      promptBlock,\n      promptIdentityTiers: promptCompiled.identityTiers,\n      broadcastEndAuthority: promptCompiled.endAuthority,\n      active: !!state.pending?.active,\n    };''', 'session prompt compile result')

old_identity = '''function runtimeIdentity(text, previous = null) {\n  const value = String(text == null ? '' : text);\n  const buckets = { stable: [], slow: [], volatile: [] };\n  for (const line of (value ? value.split('\\n') : [])) buckets[runtimeLineTier(line)].push(line);\n  const build = (name, joined) => {\n    const chars = joined.length;\n    const hash = cacheHash(joined);\n    const prior = previous?.[name];\n    const status = !prior ? 'BASELINE' : (Number(prior.chars) === chars && String(prior.hash || '') === hash ? 'SAME' : 'CHANGED');\n    return Object.freeze({ chars, hash, status });\n  };\n  return Object.freeze({\n    stable: build('stable', buckets.stable.join('\\n')),\n    slow: build('slow', buckets.slow.join('\\n')),\n    volatile: build('volatile', buckets.volatile.join('\\n')),\n    full: build('full', value),\n  });\n}'''
new_identity = '''function runtimeIdentity(text, previous = null, compilerTiers = null) {\n  const value = String(text == null ? '' : text);\n  const compilerProvided = !!compilerTiers && typeof compilerTiers === 'object';\n  let segments;\n  if (compilerProvided) {\n    segments = {\n      stable: String(compilerTiers.stable || ''),\n      slow: String(compilerTiers.slow || ''),\n      volatile: String(compilerTiers.volatile || ''),\n    };\n  } else {\n    const buckets = { stable: [], slow: [], volatile: [] };\n    for (const line of (value ? value.split('\\n') : [])) buckets[runtimeLineTier(line)].push(line);\n    segments = {\n      stable: buckets.stable.join('\\n'),\n      slow: buckets.slow.join('\\n'),\n      volatile: buckets.volatile.join('\\n'),\n    };\n  }\n  const build = (name, joined) => {\n    const chars = joined.length;\n    const hash = cacheHash(joined);\n    const prior = previous?.[name];\n    const status = !prior ? 'BASELINE' : (Number(prior.chars) === chars && String(prior.hash || '') === hash ? 'SAME' : 'CHANGED');\n    return Object.freeze({ chars, hash, status });\n  };\n  return Object.freeze({\n    source: compilerProvided ? 'COMPILER_TIERS' : 'LINE_CLASSIFIER_FALLBACK',\n    stable: build('stable', segments.stable),\n    slow: build('slow', segments.slow),\n    volatile: build('volatile', segments.volatile),\n    full: build('full', value),\n  });\n}'''
rep(old_identity, new_identity, 'runtime identity compiler tiers')

rep('''      const identity = runtimeIdentity(currentText, previousKey === currentKey ? previousIdentity : null);''', '''      const identity = runtimeIdentity(\n        currentText,\n        previousKey === currentKey ? previousIdentity : null,\n        extra?.identityTiers || null,\n      );''', 'runtime identity observe tiers')
rep('''      return { version: 1, key: previousKey, sketch: previousSketch, identity: previousIdentity };''', '''      return {\n        version: 1,\n        key: previousKey,\n        sketch: previousSketch,\n        identity: previousIdentity,\n        identityMode: previousIdentity?.source || null,\n      };''', 'runtime cache identity export mode')
rep('''      previousSketch = state.sketch;\n      previousIdentity = state.identity || null;\n      return true;''', '''      previousSketch = state.sketch;\n      previousIdentity = state.identityMode === 'COMPILER_TIERS' && state.identity?.source === 'COMPILER_TIERS'\n        ? state.identity\n        : null;\n      return true;''', 'runtime cache identity import compatibility')

rep('''  return `${part('stable')} · ${part('slow')} · ${part('volatile')} · ${part('full')}`;''', '''  return `${id.source || 'UNKNOWN'} · ${part('stable')} · ${part('slow')} · ${part('volatile')} · ${part('full')}`;''', 'runtime identity diagnostic source')

rep('''        sourceAnchor: runtimeBudgetLines.some((line) => line === 'short_community_source_is_authoritative=1'),\n        at: Date.now(),''', '''        sourceAnchor: runtimeBudgetLines.some((line) => line === 'short_community_source_is_authoritative=1'),\n        broadcastSessionState: result.broadcastEndAuthority?.session || 'CLOSED',\n        broadcastEndAuthority: result.broadcastEndAuthority?.authority || 'NOT_APPLICABLE',\n        broadcastEndReason: result.broadcastEndAuthority?.reason || 'unknown',\n        at: Date.now(),''', 'runtime budget broadcast authority')
rep('''        mode: runtimeBudgetMode,\n        at: Date.now(),''', '''        mode: runtimeBudgetMode,\n        identityTiers: result.promptIdentityTiers || null,\n        at: Date.now(),''', 'runtime cache observe compiler tiers')

rep('''      `Runtime prompt: ${probeFresh && budget ? `${Number(budget.chars || 0)} chars / ${Number(budget.lines || 0)} lines` : 'n/a'}`,\n      `Short-C source lock:''', '''      `Runtime prompt: ${probeFresh && budget ? `${Number(budget.chars || 0)} chars / ${Number(budget.lines || 0)} lines` : 'n/a'}`,\n      `Broadcast lifecycle: ${probeFresh && budget ? `${budget.broadcastSessionState || 'CLOSED'} · mode ${budget.mode || 'n/a'}` : 'n/a'}`,\n      `Broadcast end authority: ${probeFresh && budget ? `${budget.broadcastEndAuthority || 'NOT_APPLICABLE'} · ${budget.broadcastEndReason || 'unknown'}` : 'n/a'}`,\n      `End boundary: ${probeFresh && budget && budget.broadcastEndAuthority === 'DENIED' ? 'PROSE+COMMUNITY+KNOWLEDGE · explicit B_END required' : (probeFresh && budget && budget.broadcastEndAuthority === 'ALLOWED' ? 'END AUTHORIZED' : 'n/a')}`,\n      `Short-C source lock:''', 'diagnostic broadcast authority')

p.write_text(s)
Path('plugins/simcore/install.js').write_text(s)
print('patched chars', len(s))
